In [3]:
%pip install pandas
import pandas as pd

Requirement already satisfied: pandas in c:\users\rakes\python\anaconda\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\rakes\python\anaconda\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\rakes\python\anaconda\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\rakes\python\anaconda\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\rakes\python\anaconda\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\rakes\python\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
print(pd.__version__)

2.2.2

# PANDAS
  - Pandas are used to analyze the data.

##### DEF:-- Pandas is a open-source library used to analyze data , manipulate the data and cleaning the data.
             - It provides the data structures like Series and Dataframes for handling the  structured data easily.
             - Pandas library built using the numpy, which is heavily used to data Manipulation, Visualisation and building machine learning models.

##### There are two main data structures in the pandas, they are SERIES and DATA FRAMES. 
      - The default way to store the data is data frames.
      - manipulating the data quickly is one of the most important skill in data analysis

#### 1.SERIES
     - Series is a Data Structure, which has same datatypes(numeric, charecter, datetime etc..)
     - Series is like a one-dimensional array which will have column like values like excel and csv sheets.
     - ex:- Its like rows and columns in the excel sheet.
             data = [10, 20, 30, 40]
             syntax:--   pd.Series(data, index=[values])

#### 2.DATA FRAMES
     - Dataframes(DF) is a data structure which has different datatypes.
     - DF is like a two dimensional array,which has rows and columns.
     - ex:- rows and columns in the excel sheet.
          data = {'Name': ['Alice', 'Bob', 'Charlie'],
            'Age': [25, 30, 35],
            'Salary': [50000, 60000, 70000]} 
            - SYNTAX:--
                 pd.DataFrame(data, index=[values])

In [5]:
import pandas as pd
data = [10,20,30,40,50,60]
df = pd.Series(data)
print(df)

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [7]:
import pandas as pd
import numpy as np
pd.Series([20,30,40])
check_type = pd.Series([3,6,9])
type(check_type)
type(check_type.values)
check_type

0    3
1    6
2    9
dtype: int64

In [9]:
pd.Series([20,30,40],index=['a','b','c'])

a    20
b    30
c    40
dtype: int64

In [28]:
df =pd.Series(data, index=['a','b','c','x','y','z'])
print(df)

a    10
b    20
c    30
x    40
y    50
z    60
dtype: int64

In [29]:
type(df)

pandas.core.series.Series

In [41]:
import numpy as np
pd.Series(np.array(range(3,9)), index = range(0,6))

0    3
1    4
2    5
3    6
4    7
5    8
dtype: int32

# DataFrame

In [45]:
data = {
    'employe_name' : ['ven','jenni','rakesh'],
        'e_id' : [3245,2234,8795],
        '9e_loc' : ['hyd','banglore','mumbai']

    
}
data

{'employe_name': ['ven', 'jenni', 'rakesh'],
 'e_id': [3245, 2234, 8795],
 '9e_loc': ['hyd', 'banglore', 'mumbai']}

In [55]:
df = pd.DataFrame(data)
print(df)
df

  employe_name  e_id    9e_loc
0          ven  3245       hyd
1        jenni  2234  banglore
2       rakesh  8795    mumbai

  employe_name  e_id    9e_loc
0          ven  3245       hyd
1        jenni  2234  banglore
2       rakesh  8795    mumbai

In [57]:
df1 = pd.DataFrame(data, index = ['a','b','c'])
df1

  employe_name  e_id    9e_loc
a          ven  3245       hyd
b        jenni  2234  banglore
c       rakesh  8795    mumbai

In [75]:
import os
market_df = pd.read_csv(r"C:\Users\rakes\Downloads\market_fact.csv")
market_df

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
0,Ord_5446,Prod_16,SHP_7609,Cust_1818,136.8100,0.01,23,-30.51,3.60,0.56
1,Ord_5406,Prod_13,SHP_7549,Cust_1818,42.2700,0.01,13,4.56,0.93,0.54
2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.6900,0.00,26,1148.90,2.50,0.59
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.8900,0.09,43,729.34,14.30,0.37
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.1500,0.08,35,1219.87,26.30,0.38
...,...,...,...,...,...,...,...,...,...,...
8394,Ord_5353,Prod_4,SHP_7479,Cust_1798,2841.4395,0.08,28,374.63,7.69,0.59
8395,Ord_5411,Prod_6,SHP_7555,Cust_1798,127.1600,0.10,20,-74.03,6.92,0.37
8396,Ord_5388,Prod_6,SHP_7524,Cust_1798,243.0500,0.02,39,-70.85,5.35,0.40
8397,Ord_5348,Prod_15,SHP_7469,Cust_1798,3872.8700,0.03,23,565.34,30.00,0.62
8398,Ord_5459,Prod_6,SHP_7628,Cust_1798,603.6900,0.00,47,131.39,4.86,0.38

In [82]:
market_df.head(9)

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
0,Ord_5446,Prod_16,SHP_7609,Cust_1818,136.8100,0.01,23,-30.51,3.60,0.56
1,Ord_5406,Prod_13,SHP_7549,Cust_1818,42.2700,0.01,13,4.56,0.93,0.54
2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.6900,0.00,26,1148.90,2.50,0.59
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.8900,0.09,43,729.34,14.30,0.37
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.1500,0.08,35,1219.87,26.30,0.38
5,Ord_5446,Prod_6,SHP_7608,Cust_1818,164.0200,0.03,23,-47.64,6.15,0.37
6,Ord_31,Prod_12,SHP_41,Cust_26,14.7600,0.01,5,1.32,0.50,0.36
7,Ord_4725,Prod_4,SHP_6593,Cust_1641,3410.1575,0.10,48,1137.91,0.99,0.55
8,Ord_4725,Prod_13,SHP_6593,Cust_1641,162.0000,0.01,33,45.84,0.71,0.52

In [80]:
market_df.tail(6)

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
8393,Ord_5348,Prod_8,SHP_7470,Cust_1798,356.7200,0.07,9,12.61,1.99,0.44
8394,Ord_5353,Prod_4,SHP_7479,Cust_1798,2841.4395,0.08,28,374.63,7.69,0.59
8395,Ord_5411,Prod_6,SHP_7555,Cust_1798,127.1600,0.10,20,-74.03,6.92,0.37
8396,Ord_5388,Prod_6,SHP_7524,Cust_1798,243.0500,0.02,39,-70.85,5.35,0.40
8397,Ord_5348,Prod_15,SHP_7469,Cust_1798,3872.8700,0.03,23,565.34,30.00,0.62
8398,Ord_5459,Prod_6,SHP_7628,Cust_1798,603.6900,0.00,47,131.39,4.86,0.38

In [83]:
market_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8399 entries, 0 to 8398
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Ord_id               8399 non-null   object
 1   Prod_id              8399 non-null   object
 2   Ship_id              8399 non-null   object
 3   Cust_id              8399 non-null   object
 4   Sales                8399 non-null   float64
 5   Discount             8399 non-null   float64
 6   Order_Quantity       8399 non-null   int64
 7   Profit               8399 non-null   float64
 8   Shipping_Cost        8399 non-null   float64
 9   Product_Base_Margin  8336 non-null   float64
dtypes: float64(5), int64(1), object(4)
memory usage: 656.3+ KB

In [84]:
market_df.describe()

,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
count,8399.000000,8399.000000,8399.000000,8399.000000,8399.000000,8336.000000
mean,1775.878179,0.049671,25.571735,181.184424,12.838557,0.512513
std,3585.050525,0.031823,14.481071,1196.653371,17.264052,0.135589
min,2.240000,0.000000,1.000000,-14140.700000,0.490000,0.350000
25%,143.195000,0.020000,13.000000,-83.315000,3.300000,0.380000
50%,449.420000,0.050000,26.000000,-1.500000,6.070000,0.520000
75%,1709.320000,0.080000,38.000000,162.750000,13.990000,0.590000
max,89061.050000,0.250000,50.000000,27220.690000,164.730000,0.850000

In [85]:
market_df.columns

Index(['Ord_id', 'Prod_id', 'Ship_id', 'Cust_id', 'Sales', 'Discount',
       'Order_Quantity', 'Profit', 'Shipping_Cost', 'Product_Base_Margin'],
      dtype='object')

In [86]:
market_df.shape

(8399, 10)

In [102]:
market_df.values

array([['Prod_16', 'SHP_7609', 'Cust_1818', ..., -30.51, 3.6, 0.56],
       ['Prod_13', 'SHP_7549', 'Cust_1818', ..., 4.56, 0.93, 0.54],
       ['Prod_4', 'SHP_7610', 'Cust_1818', ..., 1148.9, 2.5, 0.59],
       ...,
       ['Prod_6', 'SHP_7524', 'Cust_1798', ..., -70.85, 5.35, 0.4],
       ['Prod_15', 'SHP_7469', 'Cust_1798', ..., 565.34, 30.0, 0.62],
       ['Prod_6', 'SHP_7628', 'Cust_1798', ..., 131.39, 4.86, 0.38]],
      dtype=object)

In [103]:
market_df

,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
Ord_id,,,,,,,,,
Ord_5446,Prod_16,SHP_7609,Cust_1818,136.8100,0.01,23,-30.51,3.60,0.56
Ord_5406,Prod_13,SHP_7549,Cust_1818,42.2700,0.01,13,4.56,0.93,0.54
Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.6900,0.00,26,1148.90,2.50,0.59
Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.8900,0.09,43,729.34,14.30,0.37
Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.1500,0.08,35,1219.87,26.30,0.38
...,...,...,...,...,...,...,...,...,...
Ord_5353,Prod_4,SHP_7479,Cust_1798,2841.4395,0.08,28,374.63,7.69,0.59
Ord_5411,Prod_6,SHP_7555,Cust_1798,127.1600,0.10,20,-74.03,6.92,0.37
Ord_5388,Prod_6,SHP_7524,Cust_1798,243.0500,0.02,39,-70.85,5.35,0.40
Ord_5348,Prod_15,SHP_7469,Cust_1798,3872.8700,0.03,23,565.34,30.00,0.62
Ord_5459,Prod_6,SHP_7628,Cust_1798,603.6900,0.00,47,131.39,4.86,0.38

In [104]:
#market_df.columns
#df= market_df.set_index('')

In [105]:
market_df.info

<bound method DataFrame.info of           Prod_id   Ship_id    Cust_id      Sales  Discount  Order_Quantity  \
Ord_id
Ord_5446  Prod_16  SHP_7609  Cust_1818   136.8100      0.01              23
Ord_5406  Prod_13  SHP_7549  Cust_1818    42.2700      0.01              13
Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.6900      0.00              26
Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.8900      0.09              43
Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.1500      0.08              35
...           ...       ...        ...        ...       ...             ...
Ord_5353   Prod_4  SHP_7479  Cust_1798  2841.4395      0.08              28
Ord_5411   Prod_6  SHP_7555  Cust_1798   127.1600      0.10              20
Ord_5388   Prod_6  SHP_7524  Cust_1798   243.0500      0.02              39
Ord_5348  Prod_15  SHP_7469  Cust_1798  3872.8700      0.03              23
Ord_5459   Prod_6  SHP_7628  Cust_1798   603.6900      0.00              47

           Profit  Shipping_Cost  Product_Base_Margin
Ord_id
Ord_5446   -30.51           3.60                 0.56
Ord_5406     4.56           0.93                 0.54
Ord_5446  1148.90           2.50                 0.59
Ord_5456   729.34          14.30                 0.37
Ord_5485  1219.87          26.30                 0.38
...           ...            ...                  ...
Ord_5353   374.63           7.69                 0.59
Ord_5411   -74.03           6.92                 0.37
Ord_5388   -70.85           5.35                 0.40
Ord_5348   565.34          30.00                 0.62
Ord_5459   131.39           4.86                 0.38

[8399 rows x 9 columns]>

In [106]:
market_df.columns

Index(['Prod_id', 'Ship_id', 'Cust_id', 'Sales', 'Discount', 'Order_Quantity',
       'Profit', 'Shipping_Cost', 'Product_Base_Margin'],
      dtype='object')

## Sorting data

In [109]:
market_df.sort_index(axis=0, ascending = True)

,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
Ord_id,,,,,,,,,
Ord_1,Prod_1,SHP_1,Cust_1,261.54,0.04,6,-213.25,35.00,0.80
Ord_10,Prod_3,SHP_13,Cust_10,80.61,0.02,15,-4.72,2.99,0.37
Ord_100,Prod_8,SHP_138,Cust_58,121.12,0.10,3,-118.82,1.99,0.44
Ord_1000,Prod_6,SHP_1384,Cust_373,334.71,0.01,25,31.74,6.47,0.38
Ord_1001,Prod_5,SHP_1385,Cust_374,1981.26,0.07,49,100.80,8.66,0.76
...,...,...,...,...,...,...,...,...,...
Ord_997,Prod_14,SHP_1379,Cust_365,28761.52,0.04,8,285.11,24.49,0.37
Ord_998,Prod_5,SHP_1382,Cust_372,2149.37,0.03,42,217.87,19.99,0.55
Ord_998,Prod_8,SHP_1380,Cust_372,750.66,0.00,33,120.05,4.00,0.60
Ord_998,Prod_8,SHP_1381,Cust_372,254.32,0.01,8,-117.39,6.50,0.79
Ord_999,Prod_15,SHP_1383,Cust_361,5661.08,0.00,33,1055.47,30.00,0.62

In [116]:
market_df.sort_index(axis=0, ascending = False)

,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
Ord_id,,,,,,,,,
Ord_999,Prod_15,SHP_1383,Cust_361,5661.08,0.00,33,1055.47,30.00,0.62
Ord_998,Prod_8,SHP_1380,Cust_372,750.66,0.00,33,120.05,4.00,0.60
Ord_998,Prod_5,SHP_1382,Cust_372,2149.37,0.03,42,217.87,19.99,0.55
Ord_998,Prod_8,SHP_1381,Cust_372,254.32,0.01,8,-117.39,6.50,0.79
Ord_997,Prod_14,SHP_1379,Cust_365,28761.52,0.04,8,285.11,24.49,0.37
...,...,...,...,...,...,...,...,...,...
Ord_1001,Prod_5,SHP_1385,Cust_374,1981.26,0.07,49,100.80,8.66,0.76
Ord_1000,Prod_6,SHP_1384,Cust_373,334.71,0.01,25,31.74,6.47,0.38
Ord_100,Prod_8,SHP_138,Cust_58,121.12,0.10,3,-118.82,1.99,0.44
Ord_10,Prod_3,SHP_13,Cust_10,80.61,0.02,15,-4.72,2.99,0.37
Ord_1,Prod_1,SHP_1,Cust_1,261.54,0.04,6,-213.25,35.00,0.80

In [125]:
#market_df.sort_values(by = 'Sales',ascending = True)
market_df.sort_values(by = 'Order_Quantity', ascending = False).head()   # we can use tail also.

,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
Ord_id,,,,,,,,,
Ord_1158,Prod_4,SHP_1600,Cust_445,849.031,0.07,50,-133.31,3.30,0.81
Ord_4300,Prod_6,SHP_6002,Cust_1443,490.870,0.00,50,190.93,2.03,0.37
Ord_1753,Prod_6,SHP_2430,Cust_588,1027.660,0.00,50,184.07,8.68,0.37
Ord_63,Prod_3,SHP_86,Cust_48,820.520,0.01,50,-191.22,13.18,0.37
Ord_4140,Prod_5,SHP_5766,Cust_1415,627.120,0.08,50,100.04,4.98,0.48

In [129]:
market_df.sort_values(by = ['Prod_id','Profit'], ascending = False).head()

,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
Ord_id,,,,,,,,,
Ord_2197,Prod_9,SHP_2994,Cust_827,7522.80,0.04,48,3187.37,19.99,0.39
Ord_4356,Prod_9,SHP_6074,Cust_1481,6831.72,0.01,41,3081.02,19.99,0.39
Ord_262,Prod_9,SHP_358,Cust_66,6553.45,0.03,39,2969.81,19.99,0.39
Ord_4059,Prod_9,SHP_5660,Cust_1378,5587.20,0.05,36,2254.16,19.99,0.39
Ord_2973,Prod_9,SHP_6073,Cust_1480,5410.95,0.09,36,2077.91,19.99,0.39

In [134]:
market_df.sort_values(by = ['Prod_id','Profit'], ascending = [True , False])

,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
Ord_id,,,,,,,,,
Ord_2673,Prod_1,SHP_3661,Cust_1027,21337.27,0.02,49,7606.00,19.99,0.58
Ord_2601,Prod_1,SHP_3561,Cust_1007,17874.26,0.00,41,6247.95,19.99,0.58
Ord_3581,Prod_1,SHP_4958,Cust_1264,17853.64,0.02,41,6227.33,19.99,0.58
Ord_5249,Prod_1,SHP_7330,Cust_1771,17129.97,0.07,43,5616.08,11.37,0.57
Ord_3766,Prod_1,SHP_5225,Cust_1320,15655.24,0.09,38,4818.29,19.99,0.58
...,...,...,...,...,...,...,...,...,...
Ord_3971,Prod_9,SHP_5520,Cust_1366,723.17,0.09,46,-154.11,12.39,0.35
Ord_1472,Prod_9,SHP_2033,Cust_492,365.24,0.09,44,-163.13,8.29,0.38
Ord_2737,Prod_9,SHP_3755,Cust_994,1400.91,0.09,49,-163.53,19.51,0.36
Ord_3464,Prod_9,SHP_4799,Cust_1221,414.11,0.08,49,-172.32,8.29,0.38
Ord_1652,Prod_9,SHP_2281,Cust_542,112.63,0.08,43,-201.60,6.35,0.36

## Indexing and Selecting Data
  - Selecting Rows and Columns.
  - Select Subsets of DF.

In [155]:
df = pd.DataFrame({
    'movie_name' : ['court','mad2','chhavva'],
    'collection' : ['100cr','70cr','500cr'],
    'release'    : ['27-1-2023','1-3-2024','23-3-2025']
})
#df['release'] = pd.to_datetime(df['release'], format = '%d-%m-%Y')
df

  movie_name collection    release
0      court      100cr 2023-01-27
1       mad2       70cr 2024-03-01
2    chhavva      500cr 2025-03-23

In [150]:
df['movie_name']

0      court
1       mad2
2    chhavva
Name: movie_name, dtype: object

In [151]:
df['release']

0   -1997
1   -2026
2   -2005
Name: release, dtype: int64

In [157]:
df[['movie_name', 'collection', 'release']]

  movie_name collection    release
0      court      100cr 2023-01-27
1       mad2       70cr 2024-03-01
2    chhavva      500cr 2025-03-23

## Selecting rows

In [166]:
df = pd.read_csv("C:\\Users\\rakes\\Downloads\\market_fact.csv").head()
df

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
0,Ord_5446,Prod_16,SHP_7609,Cust_1818,136.81,0.01,23,-30.51,3.60,0.56
1,Ord_5406,Prod_13,SHP_7549,Cust_1818,42.27,0.01,13,4.56,0.93,0.54
2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.69,0.00,26,1148.90,2.50,0.59
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.89,0.09,43,729.34,14.30,0.37
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.15,0.08,35,1219.87,26.30,0.38

In [181]:
#df = market_df.set_index('Ord_id', inplace = True)
df
#df.iloc[1]
df[2:8]
#df[5::2]  selecting the 5 rows with the step of 2.

,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
Ord_id,,,,,,,,,
Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.69,0.00,26,1148.90,2.5,0.59
Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.89,0.09,43,729.34,14.3,0.37
Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.15,0.08,35,1219.87,26.3,0.38

In [169]:
df.set_index('Ord_id', inplace = True)

In [170]:
df

,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
Ord_id,,,,,,,,,
Ord_5446,Prod_16,SHP_7609,Cust_1818,136.81,0.01,23,-30.51,3.60,0.56
Ord_5406,Prod_13,SHP_7549,Cust_1818,42.27,0.01,13,4.56,0.93,0.54
Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.69,0.00,26,1148.90,2.50,0.59
Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.89,0.09,43,729.34,14.30,0.37
Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.15,0.08,35,1219.87,26.30,0.38

In [180]:
df[2:6]   # this is to select the rows based on the index or indices.

,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
Ord_id,,,,,,,,,
Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.69,0.00,26,1148.90,2.5,0.59
Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.89,0.09,43,729.34,14.3,0.37
Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.15,0.08,35,1219.87,26.3,0.38

## Selecting columns

In [184]:
df['Prod_id']

Ord_id
Ord_5446    Prod_16
Ord_5406    Prod_13
Ord_5446     Prod_4
Ord_5456     Prod_6
Ord_5485    Prod_17
Name: Prod_id, dtype: object

In [189]:
type(df['Prod_id'])

pandas.core.series.Series

In [187]:
df[['Prod_id','Sales','Profit']].head()

          Prod_id    Sales   Profit
Ord_id
Ord_5446  Prod_16   136.81   -30.51
Ord_5406  Prod_13    42.27     4.56
Ord_5446   Prod_4  4701.69  1148.90
Ord_5456   Prod_6  2337.89   729.34
Ord_5485  Prod_17  4233.15  1219.87

In [190]:
type(df[['Prod_id','Sales','Profit']])

pandas.core.frame.DataFrame

## Selecting the subset of the dataframes
  - If we select the third row or any row, it will automaticlly gives error.
  - Even after changing the index as to any number we cannot get the particular element directly from the data.
  - To get the sub-elements, we have a concept called positional arguments:-- loc and iloc.

### Position or Label based indexing:-
   - TWO Main ways of indexing df:-
     1. Position based indexing by using pd.iloc()
     2. Label based indexing by using pd.loc()
   - By using both methods, we can do the below operations:-
     - Selecting single elements/cells.
     - Selecting single and multiple rows.
     - Selecting single and multiple columns.
     - Selecting multiple rows and columns.

In [193]:
df1 = pd.read_csv("C:/Users/rakes/Downloads/market_fact.csv")
df1

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
0,Ord_5446,Prod_16,SHP_7609,Cust_1818,136.8100,0.01,23,-30.51,3.60,0.56
1,Ord_5406,Prod_13,SHP_7549,Cust_1818,42.2700,0.01,13,4.56,0.93,0.54
2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.6900,0.00,26,1148.90,2.50,0.59
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.8900,0.09,43,729.34,14.30,0.37
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.1500,0.08,35,1219.87,26.30,0.38
...,...,...,...,...,...,...,...,...,...,...
8394,Ord_5353,Prod_4,SHP_7479,Cust_1798,2841.4395,0.08,28,374.63,7.69,0.59
8395,Ord_5411,Prod_6,SHP_7555,Cust_1798,127.1600,0.10,20,-74.03,6.92,0.37
8396,Ord_5388,Prod_6,SHP_7524,Cust_1798,243.0500,0.02,39,-70.85,5.35,0.40
8397,Ord_5348,Prod_15,SHP_7469,Cust_1798,3872.8700,0.03,23,565.34,30.00,0.62
8398,Ord_5459,Prod_6,SHP_7628,Cust_1798,603.6900,0.00,47,131.39,4.86,0.38

### Integer based indexing (.iloc[])
    -

In [251]:
df1.iloc[3]

Ord_id                  Ord_5456
Prod_id                   Prod_6
Ship_id                 SHP_7625
Cust_id                Cust_1818
Sales                    2337.89
Discount                    0.09
Order_Quantity                43
Profit                    729.34
Shipping_Cost               14.3
Product_Base_Margin         0.37
Name: 3, dtype: object

In [2]:
#df1.iloc[4,6]
## SYNTAX:-- iloc[row_index,column_index]= element(gives the intersetion element)
#df1.iloc[0,9]

In [207]:
df1.iloc[4,:]  # : ----> indicates selecting all the column elements of a row.

Ord_id                  Ord_5485
Prod_id                  Prod_17
Ship_id                 SHP_7664
Cust_id                Cust_1818
Sales                    4233.15
Discount                    0.08
Order_Quantity                35
Profit                   1219.87
Shipping_Cost               26.3
Product_Base_Margin         0.38
Name: 4, dtype: object

In [220]:
## SELECTING MULTIPLE ROWS USING LIST OF INDICES.
df1.iloc[[2,3,4]]  # This is to select the specific rows of the data.
df1.iloc[[-1,-2,-3]] # This is to select all the last three rows. 
df1.iloc[-3:] # This is two select all the last 3 rows.
df1.iloc[:3] # Selects all the 3 elements before 3.
df1.iloc[3:] # Selects all the elements after 3.

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.8900,0.09,43,729.34,14.30,0.37
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.1500,0.08,35,1219.87,26.30,0.38
5,Ord_5446,Prod_6,SHP_7608,Cust_1818,164.0200,0.03,23,-47.64,6.15,0.37
6,Ord_31,Prod_12,SHP_41,Cust_26,14.7600,0.01,5,1.32,0.50,0.36
7,Ord_4725,Prod_4,SHP_6593,Cust_1641,3410.1575,0.10,48,1137.91,0.99,0.55
...,...,...,...,...,...,...,...,...,...,...
8394,Ord_5353,Prod_4,SHP_7479,Cust_1798,2841.4395,0.08,28,374.63,7.69,0.59
8395,Ord_5411,Prod_6,SHP_7555,Cust_1798,127.1600,0.10,20,-74.03,6.92,0.37
8396,Ord_5388,Prod_6,SHP_7524,Cust_1798,243.0500,0.02,39,-70.85,5.35,0.40
8397,Ord_5348,Prod_15,SHP_7469,Cust_1798,3872.8700,0.03,23,565.34,30.00,0.62
8398,Ord_5459,Prod_6,SHP_7628,Cust_1798,603.6900,0.00,47,131.39,4.86,0.38

In [222]:
df1.iloc[4:8]  # .iloc[index(inclusive), index(exclusive)]

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.1500,0.08,35,1219.87,26.30,0.38
5,Ord_5446,Prod_6,SHP_7608,Cust_1818,164.0200,0.03,23,-47.64,6.15,0.37
6,Ord_31,Prod_12,SHP_41,Cust_26,14.7600,0.01,5,1.32,0.50,0.36
7,Ord_4725,Prod_4,SHP_6593,Cust_1641,3410.1575,0.10,48,1137.91,0.99,0.55

In [238]:
## Selecting multiple rows and multiple columns using range.
df1.iloc[[0,2],:]
df1.iloc[[0,3],[3,4,5]]
df1.iloc[[3,6,9],[1,2,3,4,6,7]]

   Prod_id   Ship_id    Cust_id    Sales  Order_Quantity  Profit
3   Prod_6  SHP_7625  Cust_1818  2337.89              43  729.34
6  Prod_12    SHP_41    Cust_26    14.76               5    1.32
9   Prod_6  SHP_6593  Cust_1641    57.22               8  -27.72

In [237]:
## Selecting multiple rows and columns using :
df1.iloc[0:3]
df1.iloc[1:6,3:6]
df1.iloc[3:6,:]

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.89,0.09,43,729.34,14.30,0.37
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.15,0.08,35,1219.87,26.30,0.38
5,Ord_5446,Prod_6,SHP_7608,Cust_1818,164.02,0.03,23,-47.64,6.15,0.37

#### Selecting columns

In [244]:
df1.iloc[:,3]  # column indexing also starts from 0. :--> indicates selecting all the rows.
df1.iloc[:,-1] # selecting the last column.

0       0.56
1       0.54
2       0.59
3       0.37
4       0.38
        ...
8394    0.59
8395    0.37
8396    0.40
8397    0.62
8398    0.38
Name: Product_Base_Margin, Length: 8399, dtype: float64

In [250]:
df1.iloc[:,3:6] ## Selecting multiple columns and all rows.
df1.iloc[0:2,3:6] ## Selecting multiple rows and columns.

     Cust_id   Sales  Discount
0  Cust_1818  136.81      0.01
1  Cust_1818   42.27      0.01

### Label based indexing (.loc[])

In [252]:
df1

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
0,Ord_5446,Prod_16,SHP_7609,Cust_1818,136.8100,0.01,23,-30.51,3.60,0.56
1,Ord_5406,Prod_13,SHP_7549,Cust_1818,42.2700,0.01,13,4.56,0.93,0.54
2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.6900,0.00,26,1148.90,2.50,0.59
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.8900,0.09,43,729.34,14.30,0.37
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.1500,0.08,35,1219.87,26.30,0.38
...,...,...,...,...,...,...,...,...,...,...
8394,Ord_5353,Prod_4,SHP_7479,Cust_1798,2841.4395,0.08,28,374.63,7.69,0.59
8395,Ord_5411,Prod_6,SHP_7555,Cust_1798,127.1600,0.10,20,-74.03,6.92,0.37
8396,Ord_5388,Prod_6,SHP_7524,Cust_1798,243.0500,0.02,39,-70.85,5.35,0.40
8397,Ord_5348,Prod_15,SHP_7469,Cust_1798,3872.8700,0.03,23,565.34,30.00,0.62
8398,Ord_5459,Prod_6,SHP_7628,Cust_1798,603.6900,0.00,47,131.39,4.86,0.38

In [253]:
df1.loc[2,'Sales']

4701.69

In [254]:
df1.loc[5]

Ord_id                  Ord_5446
Prod_id                   Prod_6
Ship_id                 SHP_7608
Cust_id                Cust_1818
Sales                     164.02
Discount                    0.03
Order_Quantity                23
Profit                    -47.64
Shipping_Cost               6.15
Product_Base_Margin         0.37
Name: 5, dtype: object

In [256]:
df1.loc[[3,6,9], :]

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.89,0.09,43,729.34,14.3,0.37
6,Ord_31,Prod_12,SHP_41,Cust_26,14.76,0.01,5,1.32,0.5,0.36
9,Ord_4725,Prod_6,SHP_6593,Cust_1641,57.22,0.07,8,-27.72,6.6,0.37

In [260]:
df1

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
0,Ord_5446,Prod_16,SHP_7609,Cust_1818,136.8100,0.01,23,-30.51,3.60,0.56
1,Ord_5406,Prod_13,SHP_7549,Cust_1818,42.2700,0.01,13,4.56,0.93,0.54
2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.6900,0.00,26,1148.90,2.50,0.59
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.8900,0.09,43,729.34,14.30,0.37
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.1500,0.08,35,1219.87,26.30,0.38
...,...,...,...,...,...,...,...,...,...,...
8394,Ord_5353,Prod_4,SHP_7479,Cust_1798,2841.4395,0.08,28,374.63,7.69,0.59
8395,Ord_5411,Prod_6,SHP_7555,Cust_1798,127.1600,0.10,20,-74.03,6.92,0.37
8396,Ord_5388,Prod_6,SHP_7524,Cust_1798,243.0500,0.02,39,-70.85,5.35,0.40
8397,Ord_5348,Prod_15,SHP_7469,Cust_1798,3872.8700,0.03,23,565.34,30.00,0.62
8398,Ord_5459,Prod_6,SHP_7628,Cust_1798,603.6900,0.00,47,131.39,4.86,0.38

In [267]:
df1

,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
Ord_id,,,,,,,,,
Ord_5446,Prod_16,SHP_7609,Cust_1818,136.8100,0.01,23,-30.51,3.60,0.56
Ord_5406,Prod_13,SHP_7549,Cust_1818,42.2700,0.01,13,4.56,0.93,0.54
Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.6900,0.00,26,1148.90,2.50,0.59
Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.8900,0.09,43,729.34,14.30,0.37
Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.1500,0.08,35,1219.87,26.30,0.38
...,...,...,...,...,...,...,...,...,...
Ord_5353,Prod_4,SHP_7479,Cust_1798,2841.4395,0.08,28,374.63,7.69,0.59
Ord_5411,Prod_6,SHP_7555,Cust_1798,127.1600,0.10,20,-74.03,6.92,0.37
Ord_5388,Prod_6,SHP_7524,Cust_1798,243.0500,0.02,39,-70.85,5.35,0.40
Ord_5348,Prod_15,SHP_7469,Cust_1798,3872.8700,0.03,23,565.34,30.00,0.62
Ord_5459,Prod_6,SHP_7628,Cust_1798,603.6900,0.00,47,131.39,4.86,0.38

In [273]:
# Selecting rows, Based on the label.
df1.loc['Ord_5456']
# Selecting multiple columns and rows, Based on the label
df1.loc['Ord_5446', ['Sales','Profit']]

            Sales   Profit
Ord_id
Ord_5446   136.81   -30.51
Ord_5446  4701.69  1148.90
Ord_5446   164.02   -47.64

In [276]:
#selecting rows and some required columns.
df1.loc['Ord_5446','Sales':'Profit']

            Sales  Discount  Order_Quantity   Profit
Ord_id
Ord_5446   136.81      0.01              23   -30.51
Ord_5446  4701.69      0.00              26  1148.90
Ord_5446   164.02      0.03              23   -47.64

In [283]:
# selecting multiple rows and columns.
df1.loc[['Ord_5485','Ord_5411','Ord_53'],'Sales':'Profit']
df1.loc[['Ord_5446','Ord_5411'],['Sales','Profit']]

            Sales   Profit
Ord_id
Ord_5446   136.81   -30.51
Ord_5446  4701.69  1148.90
Ord_5446   164.02   -47.64
Ord_5411   127.16   -74.03

In [284]:
df1

,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
Ord_id,,,,,,,,,
Ord_5446,Prod_16,SHP_7609,Cust_1818,136.8100,0.01,23,-30.51,3.60,0.56
Ord_5406,Prod_13,SHP_7549,Cust_1818,42.2700,0.01,13,4.56,0.93,0.54
Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.6900,0.00,26,1148.90,2.50,0.59
Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.8900,0.09,43,729.34,14.30,0.37
Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.1500,0.08,35,1219.87,26.30,0.38
...,...,...,...,...,...,...,...,...,...
Ord_5353,Prod_4,SHP_7479,Cust_1798,2841.4395,0.08,28,374.63,7.69,0.59
Ord_5411,Prod_6,SHP_7555,Cust_1798,127.1600,0.10,20,-74.03,6.92,0.37
Ord_5388,Prod_6,SHP_7524,Cust_1798,243.0500,0.02,39,-70.85,5.35,0.40
Ord_5348,Prod_15,SHP_7469,Cust_1798,3872.8700,0.03,23,565.34,30.00,0.62
Ord_5459,Prod_6,SHP_7628,Cust_1798,603.6900,0.00,47,131.39,4.86,0.38

In [292]:
df1.reset_index(drop = True,inplace = False)

,level_0,index,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
0,0,0,Ord_5446,Prod_16,SHP_7609,Cust_1818,136.8100,0.01,23,-30.51,3.60,0.56
1,1,1,Ord_5406,Prod_13,SHP_7549,Cust_1818,42.2700,0.01,13,4.56,0.93,0.54
2,2,2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.6900,0.00,26,1148.90,2.50,0.59
3,3,3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.8900,0.09,43,729.34,14.30,0.37
4,4,4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.1500,0.08,35,1219.87,26.30,0.38
...,...,...,...,...,...,...,...,...,...,...,...,...
8394,8394,8394,Ord_5353,Prod_4,SHP_7479,Cust_1798,2841.4395,0.08,28,374.63,7.69,0.59
8395,8395,8395,Ord_5411,Prod_6,SHP_7555,Cust_1798,127.1600,0.10,20,-74.03,6.92,0.37
8396,8396,8396,Ord_5388,Prod_6,SHP_7524,Cust_1798,243.0500,0.02,39,-70.85,5.35,0.40
8397,8397,8397,Ord_5348,Prod_15,SHP_7469,Cust_1798,3872.8700,0.03,23,565.34,30.00,0.62
8398,8398,8398,Ord_5459,Prod_6,SHP_7628,Cust_1798,603.6900,0.00,47,131.39,4.86,0.38

In [296]:
df1.drop('index',axis = 1,inplace = True)

In [294]:
df1

,index,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
0,0,Ord_5446,Prod_16,SHP_7609,Cust_1818,136.8100,0.01,23,-30.51,3.60,0.56
1,1,Ord_5406,Prod_13,SHP_7549,Cust_1818,42.2700,0.01,13,4.56,0.93,0.54
2,2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.6900,0.00,26,1148.90,2.50,0.59
3,3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.8900,0.09,43,729.34,14.30,0.37
4,4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.1500,0.08,35,1219.87,26.30,0.38
...,...,...,...,...,...,...,...,...,...,...,...
8394,8394,Ord_5353,Prod_4,SHP_7479,Cust_1798,2841.4395,0.08,28,374.63,7.69,0.59
8395,8395,Ord_5411,Prod_6,SHP_7555,Cust_1798,127.1600,0.10,20,-74.03,6.92,0.37
8396,8396,Ord_5388,Prod_6,SHP_7524,Cust_1798,243.0500,0.02,39,-70.85,5.35,0.40
8397,8397,Ord_5348,Prod_15,SHP_7469,Cust_1798,3872.8700,0.03,23,565.34,30.00,0.62
8398,8398,Ord_5459,Prod_6,SHP_7628,Cust_1798,603.6900,0.00,47,131.39,4.86,0.38

In [297]:
df1

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
0,Ord_5446,Prod_16,SHP_7609,Cust_1818,136.8100,0.01,23,-30.51,3.60,0.56
1,Ord_5406,Prod_13,SHP_7549,Cust_1818,42.2700,0.01,13,4.56,0.93,0.54
2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.6900,0.00,26,1148.90,2.50,0.59
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.8900,0.09,43,729.34,14.30,0.37
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.1500,0.08,35,1219.87,26.30,0.38
...,...,...,...,...,...,...,...,...,...,...
8394,Ord_5353,Prod_4,SHP_7479,Cust_1798,2841.4395,0.08,28,374.63,7.69,0.59
8395,Ord_5411,Prod_6,SHP_7555,Cust_1798,127.1600,0.10,20,-74.03,6.92,0.37
8396,Ord_5388,Prod_6,SHP_7524,Cust_1798,243.0500,0.02,39,-70.85,5.35,0.40
8397,Ord_5348,Prod_15,SHP_7469,Cust_1798,3872.8700,0.03,23,565.34,30.00,0.62
8398,Ord_5459,Prod_6,SHP_7628,Cust_1798,603.6900,0.00,47,131.39,4.86,0.38

In [299]:
head_df=df1.head(5)
head_df

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
0,Ord_5446,Prod_16,SHP_7609,Cust_1818,136.81,0.01,23,-30.51,3.60,0.56
1,Ord_5406,Prod_13,SHP_7549,Cust_1818,42.27,0.01,13,4.56,0.93,0.54
2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.69,0.00,26,1148.90,2.50,0.59
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.89,0.09,43,729.34,14.30,0.37
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.15,0.08,35,1219.87,26.30,0.38

In [305]:
##using booleans
# this will select the rows corresponding to true
head_df.loc[[True,False,True,False,True]]

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
0,Ord_5446,Prod_16,SHP_7609,Cust_1818,136.81,0.01,23,-30.51,3.6,0.56
2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.69,0.00,26,1148.90,2.5,0.59
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.15,0.08,35,1219.87,26.3,0.38

In [1]:
import warnings 
warnings.filterwarnings('ignore')

#### Slicing and Dicing the elements.
    - Methods used:-
      - df.iloc[]
      - df.loc[]
      - df[]

#### Subsetting the rows based on the conditions

In [5]:
## selecting the sales 2000>sales<3000
import pandas as pd
df=pd.read_csv(r"C:\Users\rakes\Downloads\market_fact.csv")
df

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
0,Ord_5446,Prod_16,SHP_7609,Cust_1818,136.8100,0.01,23,-30.51,3.60,0.56
1,Ord_5406,Prod_13,SHP_7549,Cust_1818,42.2700,0.01,13,4.56,0.93,0.54
2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.6900,0.00,26,1148.90,2.50,0.59
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.8900,0.09,43,729.34,14.30,0.37
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.1500,0.08,35,1219.87,26.30,0.38
...,...,...,...,...,...,...,...,...,...,...
8394,Ord_5353,Prod_4,SHP_7479,Cust_1798,2841.4395,0.08,28,374.63,7.69,0.59
8395,Ord_5411,Prod_6,SHP_7555,Cust_1798,127.1600,0.10,20,-74.03,6.92,0.37
8396,Ord_5388,Prod_6,SHP_7524,Cust_1798,243.0500,0.02,39,-70.85,5.35,0.40
8397,Ord_5348,Prod_15,SHP_7469,Cust_1798,3872.8700,0.03,23,565.34,30.00,0.62
8398,Ord_5459,Prod_6,SHP_7628,Cust_1798,603.6900,0.00,47,131.39,4.86,0.38

In [8]:
# Selecting sales > 3000/-
df[df.Sales>3000]

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.6900,0.00,26,1148.90,2.50,0.59
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.1500,0.08,35,1219.87,26.30,0.38
7,Ord_4725,Prod_4,SHP_6593,Cust_1641,3410.1575,0.10,48,1137.91,0.99,0.55
10,Ord_4743,Prod_2,SHP_6615,Cust_1641,4072.0100,0.01,43,1675.98,0.99,0.56
13,Ord_2207,Prod_11,SHP_3093,Cust_839,3364.2480,0.10,15,-693.23,61.76,0.78
...,...,...,...,...,...,...,...,...,...,...
8366,Ord_3593,Prod_3,SHP_4974,Cust_1274,12073.0600,0.03,39,5081.87,19.99,0.38
8367,Ord_3593,Prod_15,SHP_4975,Cust_1274,6685.0500,0.09,25,1653.60,24.49,NaN
8371,Ord_2624,Prod_4,SHP_3591,Cust_1006,4924.1350,0.07,28,1049.54,8.99,0.58
8383,Ord_2722,Prod_1,SHP_3731,Cust_1006,3508.3300,0.04,21,-546.98,35.00,0.85
8397,Ord_5348,Prod_15,SHP_7469,Cust_1798,3872.8700,0.03,23,565.34,30.00,0.62

In [14]:
# Selecting sales, 2000>sales<3000 , profit>100
df[(df.Sales>2000) & (df.Sales<3000) & (df.Profit > 100)]

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.8900,0.09,43,729.34,14.30,0.37
81,Ord_5205,Prod_4,SHP_7274,Cust_1749,2546.5235,0.09,26,210.00,7.69,0.59
109,Ord_139,Prod_17,SHP_186,Cust_45,2671.2100,0.06,14,636.18,15.59,0.36
110,Ord_239,Prod_4,SHP_332,Cust_45,2157.3085,0.00,38,519.25,5.31,0.57
141,Ord_1673,Prod_17,SHP_2314,Cust_498,2027.5500,0.04,14,537.40,13.99,0.37
...,...,...,...,...,...,...,...,...,...,...
8338,Ord_2107,Prod_2,SHP_2882,Cust_785,2409.9600,0.07,32,575.10,4.50,0.59
8350,Ord_3570,Prod_4,SHP_4942,Cust_1266,2094.9780,0.06,44,697.29,1.25,0.55
8354,Ord_3592,Prod_4,SHP_4973,Cust_1266,2614.3705,0.07,25,384.01,7.69,0.58
8381,Ord_2696,Prod_4,SHP_3691,Cust_1006,2836.0505,0.01,25,561.13,8.99,0.59
8394,Ord_5353,Prod_4,SHP_7479,Cust_1798,2841.4395,0.08,28,374.63,7.69,0.59

In [18]:
# 2000<sales,or profit >100
df[(df.Sales<2000) | (df.Profit>100)]

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
0,Ord_5446,Prod_16,SHP_7609,Cust_1818,136.8100,0.01,23,-30.51,3.60,0.56
1,Ord_5406,Prod_13,SHP_7549,Cust_1818,42.2700,0.01,13,4.56,0.93,0.54
2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.6900,0.00,26,1148.90,2.50,0.59
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.8900,0.09,43,729.34,14.30,0.37
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.1500,0.08,35,1219.87,26.30,0.38
...,...,...,...,...,...,...,...,...,...,...
8394,Ord_5353,Prod_4,SHP_7479,Cust_1798,2841.4395,0.08,28,374.63,7.69,0.59
8395,Ord_5411,Prod_6,SHP_7555,Cust_1798,127.1600,0.10,20,-74.03,6.92,0.37
8396,Ord_5388,Prod_6,SHP_7524,Cust_1798,243.0500,0.02,39,-70.85,5.35,0.40
8397,Ord_5348,Prod_15,SHP_7469,Cust_1798,3872.8700,0.03,23,565.34,30.00,0.62
8398,Ord_5459,Prod_6,SHP_7628,Cust_1798,603.6900,0.00,47,131.39,4.86,0.38

In [27]:
# Selecting the required columns and rows.
## 2000>Sales<3000
## selecting the sales,discount, order_quantity, and profit columns.
df.loc[(df.Sales>2000)&(df.Sales<3000)&(df.Profit>100),['Sales','Discount','Order_Quantity','Profit']]

          Sales  Discount  Order_Quantity  Profit
3     2337.8900      0.09              43  729.34
81    2546.5235      0.09              26  210.00
109   2671.2100      0.06              14  636.18
110   2157.3085      0.00              38  519.25
141   2027.5500      0.04              14  537.40
...         ...       ...             ...     ...
8338  2409.9600      0.07              32  575.10
8350  2094.9780      0.06              44  697.29
8354  2614.3705      0.07              25  384.01
8381  2836.0505      0.01              25  561.13
8394  2841.4395      0.08              28  374.63

[328 rows x 4 columns]

In [31]:
## Using == and !==
df[df.Profit == 636.18]

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
109,Ord_139,Prod_17,SHP_186,Cust_45,2671.21,0.06,14,636.18,15.59,0.36

In [33]:
df[df.Profit != 636.18]

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
0,Ord_5446,Prod_16,SHP_7609,Cust_1818,136.8100,0.01,23,-30.51,3.60,0.56
1,Ord_5406,Prod_13,SHP_7549,Cust_1818,42.2700,0.01,13,4.56,0.93,0.54
2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.6900,0.00,26,1148.90,2.50,0.59
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.8900,0.09,43,729.34,14.30,0.37
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.1500,0.08,35,1219.87,26.30,0.38
...,...,...,...,...,...,...,...,...,...,...
8394,Ord_5353,Prod_4,SHP_7479,Cust_1798,2841.4395,0.08,28,374.63,7.69,0.59
8395,Ord_5411,Prod_6,SHP_7555,Cust_1798,127.1600,0.10,20,-74.03,6.92,0.37
8396,Ord_5388,Prod_6,SHP_7524,Cust_1798,243.0500,0.02,39,-70.85,5.35,0.40
8397,Ord_5348,Prod_15,SHP_7469,Cust_1798,3872.8700,0.03,23,565.34,30.00,0.62
8398,Ord_5459,Prod_6,SHP_7628,Cust_1798,603.6900,0.00,47,131.39,4.86,0.38

In [35]:
## For instance, a businessman has given some customer id's from a particular region, so based on the cust_id we need to find out the customer data.
## By using .isin() function, we can find it out easily.

customer_ids = ['Cust_1818','Cust_1749','Cust_45','Cust_1266','Cust_1006','Cust_498']
df[df['Cust_id'].isin(customer_ids)]

,Ord_id,Prod_id,Ship_id,Cust_id,Sales,Discount,Order_Quantity,Profit,Shipping_Cost,Product_Base_Margin
0,Ord_5446,Prod_16,SHP_7609,Cust_1818,136.8100,0.01,23,-30.51,3.60,0.56
1,Ord_5406,Prod_13,SHP_7549,Cust_1818,42.2700,0.01,13,4.56,0.93,0.54
2,Ord_5446,Prod_4,SHP_7610,Cust_1818,4701.6900,0.00,26,1148.90,2.50,0.59
3,Ord_5456,Prod_6,SHP_7625,Cust_1818,2337.8900,0.09,43,729.34,14.30,0.37
4,Ord_5485,Prod_17,SHP_7664,Cust_1818,4233.1500,0.08,35,1219.87,26.30,0.38
...,...,...,...,...,...,...,...,...,...,...
8379,Ord_2722,Prod_5,SHP_3730,Cust_1006,1008.9500,0.04,41,69.31,8.99,0.50
8380,Ord_2772,Prod_6,SHP_3807,Cust_1006,308.9200,0.04,45,-143.58,7.37,0.37
8381,Ord_2696,Prod_4,SHP_3691,Cust_1006,2836.0505,0.01,25,561.13,8.99,0.59
8382,Ord_2658,Prod_3,SHP_3636,Cust_1006,120.9800,0.00,28,-92.85,5.34,0.38
8383,Ord_2722,Prod_1,SHP_3731,Cust_1006,3508.3300,0.04,21,-546.98,35.00,0.85